# Generated by Django 4.1.2 on 2022-10-10 02:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keeper', '0001_initial'),
        ('animal', '0002_animal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='uploads/animal_gallery/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('for_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_animal', to='animal.animal')),
                ('for_keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_keeper', to='keeper.animalkeeper')),
            ],
        ),
    ]
