# Generated by Django 4.1.2 on 2022-10-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/animal/'),
            preserve_default=False,
        ),
    ]
